on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # set a lowercase image repo like: ghcr.io/heynand0/hello-devops
      - name: Set lowercase image repo
        run: |
          echo "IMAGE_REPO=ghcr.io/$(echo '${GITHUB_REPOSITORY}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        # $GITHUB_ENV exports variables to later steps

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      - run: go mod tidy
      - run: go test ./...

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/hello-devops:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/hello-devops:latest
